version: '3'

services:
  bot:
    build: .
    restart: always
    volumes:
      - ./dbdata:/usr/src/app/data
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    depends_on:
      - sqlite-db

  sqlite-db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./dbdata:/dbdata
    command: -init /dbdata/words.db